### ISSUE TITLE
findExpense null pointer exception. addExpense, addAllowance show incorrect message

### ISSUE THREAD

**Issue by yunjun199321** [CS2103-AY1819S2-W17-4/main#248] opened 2019-04-11 08:58 UTC
**Describe the bug**
1. findExpense n/food $/ t/ , enter. Causes null pointer exception error.

command don't handle the empty parameters. 
everyone pls check your commands and handle the empty parameters.

**Comment by tehwenyi** [comment] 2019-04-11 09:00
What error message should it be?

**Comment by yunjun199321** [comment] 2019-04-11 09:08
I think add commands are ok

**Comment by rahulb99** [comment] 2019-04-11 15:20
but this is not a bug, i have mentioned in the UG that keywords cannot be empty. anyways, fixed in my latest PR...

**Closed** 2019-04-13 02:53 UTC
Labels: type.Bug
